version: '3.8'

services:
  db:
    image: mongo:7.0.9
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - artstore-network

  app:
    build: .
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:Misha2015@artshop.ax4fwuw.mongodb.net/?retryWrites=true&w=majority&appName=ArtShop
    depends_on:
      - db
    networks:
      - artstore-network

volumes:
  mongodb_data:

networks:
  artstore-network:
    driver: bridge